#!/bin/bash

# less_termcap
#
# Colors for 'less pager'.
#
# Michael Gilchrist (michaelgilch@gmail.com)

export LESS_TERMCAP_mb=$'\E[0;31m'          # enter blink-mode
export LESS_TERMCAP_md=$'\E[0;38;5;74m'     # enter bold-mode
export LESS_TERMCAP_us=$'\E[04;38;5;146m'   # enter underline-mode
export LESS_TERMCAP_so=$'\E[1;33m'          # enter standout-mode

export LESS_TERMCAP_me=$'\E[0m'         	# end appearance-modes
export LESS_TERMCAP_se=$'\E[0m'         	# end standout-mode
export LESS_TERMCAP_ue=$'\E[0m'         	# end underline-mode


