#
# ~/.bashrc
#
# Interactive Shell Configuration
#
# This is sourced by the login shell (bash_profile). Any intended difference
# in behavior between a Login and Interactive shell should be handled 
# appropriately here.
#
# Author: Michael Gilchrist (michaelgilch@gmail.com)

PS1='[\u@\h \W]\$ '

export EDITOR="vim"
export VISUAL="$EDITOR"
export MANPAGER="less --no-init"
export PATH=$HOME/.npm-global/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH

export DOTFILES="$HOME/git/dotfiles"

# History
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=100000
HISTFILESIZE=$HISTSIZE
HISTIGNORE="clear:c:history:h:exit"
shopt -s histappend

# Additional Sources
[ -f "$HOME"/.bash_aliases ] && source "$HOME"/.bash_aliases
[ -f "$HOME"/.bash_prompt ] && source "$HOME"/.bash_prompt
