#!/bin/bash

# bash_aliases
# 
# Lengthy and complex aliases should be moved to 'bash_functions'.
# 
# Michael Gilchrist (michaelgilch@gmail.com)

# Add Color
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias pacman='pacman --color=auto'

# Lists
alias la='ls --almost-all'
alias ld='ls --directory */'
alias ll='ls -l --human-readable'
alias lla='ls -l --human-readable --almost-all'
alias lt='ls -l --sort=time --human-readable --reverse'

# Find
alias f='find . -name'      # find in current directory
alias ff='find / -name'     # find in root

# Git
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log --oneline'
alias gp='git push'
alias gr='git rm'
alias gs='git status --short --branch'

# Vim
alias vi='vim'
alias nvi='vim -N -u NONE -i NONE'  # skip vimrc/viminfo, but use no-compatible

# Misc
alias c='clear'
alias df='df --human-readable --print-type --exclude-type=tmpfs --exclude-type=devtmpfs'  
alias mkdir='mkdir --parents --verbose'
alias sudo='sudo '                      # enables aliases to be sudoed
alias sync='sync; sync'
alias mounted='mount | grep '^/dev/' | sort'
alias umount='sudo umount'
alias used='du --summarize --human-readable * | sort -h'         # list directories by human readable size
alias wget='wget --continue'

