#!/bin/bash

# prompts
# 
# PS* and Git Prompt Definitions
# 
# Michael Gilchrist (michaelgilch@gmail.com)

RED='\[\033[31m\]'
GREEN='\[\033[32m\]'
YELLOW='\[\033[33m\]'
BLUE='\[\033[34m\]'
WHITE='\[\033[97m\]'
BOLD_RED='\[\033[1;31m\]'
BOLD_GREEN='\[\033[1;32m\]'
BOLD_YELLOW='\[\033[1;33m\]'
BOLD_BLUE='\[\033[1;34m\]'
BOLD_WHITE='\[\033[1;97m\]'
RESET='\[\033[0m\]'

# Sets the title of the terminal window to the current working directory
set_title()
{
    echo -ne "\033]0;${PWD/*\//}\007"
}

# Adds git branch and status info to prompt
set_git_prompt()
{
    GIT_INFO=""
    if [ "$(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}")" == 0 ]; then
        branchName="$(git branch --quiet 2>/dev/null | grep "\*" | sed 's/\*//g' | sed 's/ //g')"
        numStaged="$(git diff --cached --numstat | wc -l)"
        numModified="$(git diff-files | wc -l)"
        numUntracked="$(git status --short | grep '^??' | wc -l)"

        GIT_INFO="${BLUE}[${WHITE}${branchName}${RESET}"

        if [[ $numStaged+$numModified+$numUntracked -gt 0 ]]; then
            if [[ $numStaged -gt 0 ]]; then
                GIT_INFO+="${GREEN}+${numStaged}"
            fi
            if [[ $numModified -gt 0 ]]; then
                GIT_INFO+="${YELLOW}!${numModified}"
            fi
            if [[ $numUntracked -gt 0 ]]; then
                GIT_INFO+="${RED}?${numUntracked}"
            fi
        fi
        GIT_INFO+="${BLUE}] ${RESET}"
    fi   
    PS1="${USER_PROMPT}${AT_SYMBOL}${HOST_PROMPT}${PATH_PROMPT}${GIT_INFO}${END_SYMBOL}"
}

prompt_command_setup()
{
    # Set title of window
    set_title

    # Set prompt
    set_git_prompt
}

USER_PROMPT="${BOLD_GREEN}\u${RESET}"
HOST_PROMPT="${BOLD_GREEN}\h${RESET}"
PATH_PROMPT="${BOLD_BLUE} \w ${RESET}"

AT_SYMBOL="${BOLD_BLUE}@${RESET}"
END_SYMBOL="${BOLD_BLUE}\$ ${RESET}"

PROMPT_COMMAND=prompt_command_setup
