#!/bin/bash

# bash_profile
#
# Login shell configuration
#
# Sources Interactive Shell Configuration (bashrc), where 
# Login vs Interactive differences will be handled accordingly.
#
# Michael Gilchrist (michaelgilch@gmail.com)

[[ -f "$HOME"/.bashrc ]] && source "$HOME"/.bashrc
