#!/bin/bash

# bash_aliases
# 
# Lengthy and complex aliases should be moved to 'bash_functions'.
# 
# Michael Gilchrist (michaelgilch@gmail.com)

# Color
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias pacman='pacman --color=auto'

# List
alias l.='ls --directory .*'
alias la='ls --almost-all'
alias ld='ls --directory */'
alias ll='ls -l --human-readable'
alias ll.='ls -l --directory .*'
alias lla='ls -l --human-readable --almost-all'
alias lls='ls -l --sort=size --human-readable --reverse'
alias llt='ls -l --sort=time --human-readable --reverse'

# Find
alias f='find . -name'      # find in current directory
alias ff='find / -name'     # find in root

# Git
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias gl='git log --oneline'
alias gp='git push'
alias gr='git rm'
alias gs='git status'
alias gb='git checkout -b'
alias gss='git status --short --branch'

# Vim
alias vi='vim'
alias nvi='vim -N -u NONE -i NONE'  # skip vimrc/viminfo, but use no-compatible

# Misc
alias c='clear'                         # clear the terminal
alias cpu='sensors | grep Core'         # display CPU temps
alias df='df -hT -x tmpfs -x devtmpfs'  # human readable, show partition type
alias mkdir='mkdir -pv'                 # make parents, verbose
alias myip='curl ifconfig.co'           # external ip
alias path='echo -e ${PATH//:/\\n}'     # PATH as newline separated list
alias sudo='sudo '                      # enables aliases to be sudoed
alias umount='sudo umount'              # easier unmounting
alias upgrade='sudo pacman -Syu'        # upgrade packages
alias used='du -sh * | sort -h'         # list directories by human readable size
alias wget='wget -c'                    # continue partial downloads

# Navigation
alias aur='cd ~/.aur/'
alias dev='cd ~/dev/'
alias github='cd ~/dev/github/'
alias dot='cd ~/dev/github/dotfiles/'
alias notes='cd ~/dev/github/notes/'
alias pdfm='cd ~/dev/github/pdfm/'
